// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package mod

import (
	"time"
)

type CustomerSignupRequest struct {
	FullName    string     `json:"fullName"`
	CountryCode string     `json:"countryCode"`
	PhoneNumber string     `json:"phoneNumber"`
	Password    string     `json:"password"`
	DateOfBirth *time.Time `json:"dateOfBirth,omitempty"`
}

type CustomerSignupResponse struct {
	IamID int64 `json:"iamID"`
}

type Mutation struct {
}

type Query struct {
}
