// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

var TableNames = struct {
	Categories       string
	MenuItemOptions  string
	MenuItemPrices   string
	MenuItems        string
	SchemaMigrations string
}{
	Categories:       "categories",
	MenuItemOptions:  "menu_item_options",
	MenuItemPrices:   "menu_item_prices",
	MenuItems:        "menu_items",
	SchemaMigrations: "schema_migrations",
}
