// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// MenuItemPrice is an object representing the database table.
type MenuItemPrice struct {
	ID         int64         `boil:"id" json:"id" toml:"id" yaml:"id"`
	MenuItemID int64         `boil:"menu_item_id" json:"menu_item_id" toml:"menu_item_id" yaml:"menu_item_id"`
	Size       string        `boil:"size" json:"size" toml:"size" yaml:"size"`
	Price      types.Decimal `boil:"price" json:"price" toml:"price" yaml:"price"`
	CreatedAt  time.Time     `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt  time.Time     `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *menuItemPriceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L menuItemPriceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MenuItemPriceColumns = struct {
	ID         string
	MenuItemID string
	Size       string
	Price      string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "id",
	MenuItemID: "menu_item_id",
	Size:       "size",
	Price:      "price",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

var MenuItemPriceTableColumns = struct {
	ID         string
	MenuItemID string
	Size       string
	Price      string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "menu_item_prices.id",
	MenuItemID: "menu_item_prices.menu_item_id",
	Size:       "menu_item_prices.size",
	Price:      "menu_item_prices.price",
	CreatedAt:  "menu_item_prices.created_at",
	UpdatedAt:  "menu_item_prices.updated_at",
}

// Generated where

type whereHelpertypes_Decimal struct{ field string }

func (w whereHelpertypes_Decimal) EQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_Decimal) NEQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_Decimal) LT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_Decimal) LTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_Decimal) GT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_Decimal) GTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var MenuItemPriceWhere = struct {
	ID         whereHelperint64
	MenuItemID whereHelperint64
	Size       whereHelperstring
	Price      whereHelpertypes_Decimal
	CreatedAt  whereHelpertime_Time
	UpdatedAt  whereHelpertime_Time
}{
	ID:         whereHelperint64{field: "\"menu_item_prices\".\"id\""},
	MenuItemID: whereHelperint64{field: "\"menu_item_prices\".\"menu_item_id\""},
	Size:       whereHelperstring{field: "\"menu_item_prices\".\"size\""},
	Price:      whereHelpertypes_Decimal{field: "\"menu_item_prices\".\"price\""},
	CreatedAt:  whereHelpertime_Time{field: "\"menu_item_prices\".\"created_at\""},
	UpdatedAt:  whereHelpertime_Time{field: "\"menu_item_prices\".\"updated_at\""},
}

// MenuItemPriceRels is where relationship names are stored.
var MenuItemPriceRels = struct {
	MenuItem string
}{
	MenuItem: "MenuItem",
}

// menuItemPriceR is where relationships are stored.
type menuItemPriceR struct {
	MenuItem *MenuItem `boil:"MenuItem" json:"MenuItem" toml:"MenuItem" yaml:"MenuItem"`
}

// NewStruct creates a new relationship struct
func (*menuItemPriceR) NewStruct() *menuItemPriceR {
	return &menuItemPriceR{}
}

func (r *menuItemPriceR) GetMenuItem() *MenuItem {
	if r == nil {
		return nil
	}
	return r.MenuItem
}

// menuItemPriceL is where Load methods for each relationship are stored.
type menuItemPriceL struct{}

var (
	menuItemPriceAllColumns            = []string{"id", "menu_item_id", "size", "price", "created_at", "updated_at"}
	menuItemPriceColumnsWithoutDefault = []string{"id", "menu_item_id", "size", "price"}
	menuItemPriceColumnsWithDefault    = []string{"created_at", "updated_at"}
	menuItemPricePrimaryKeyColumns     = []string{"id"}
	menuItemPriceGeneratedColumns      = []string{}
)

type (
	// MenuItemPriceSlice is an alias for a slice of pointers to MenuItemPrice.
	// This should almost always be used instead of []MenuItemPrice.
	MenuItemPriceSlice []*MenuItemPrice

	menuItemPriceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	menuItemPriceType                 = reflect.TypeOf(&MenuItemPrice{})
	menuItemPriceMapping              = queries.MakeStructMapping(menuItemPriceType)
	menuItemPricePrimaryKeyMapping, _ = queries.BindMapping(menuItemPriceType, menuItemPriceMapping, menuItemPricePrimaryKeyColumns)
	menuItemPriceInsertCacheMut       sync.RWMutex
	menuItemPriceInsertCache          = make(map[string]insertCache)
	menuItemPriceUpdateCacheMut       sync.RWMutex
	menuItemPriceUpdateCache          = make(map[string]updateCache)
	menuItemPriceUpsertCacheMut       sync.RWMutex
	menuItemPriceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single menuItemPrice record from the query.
func (q menuItemPriceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MenuItemPrice, error) {
	o := &MenuItemPrice{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodel: failed to execute a one query for menu_item_prices")
	}

	return o, nil
}

// All returns all MenuItemPrice records from the query.
func (q menuItemPriceQuery) All(ctx context.Context, exec boil.ContextExecutor) (MenuItemPriceSlice, error) {
	var o []*MenuItemPrice

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodel: failed to assign all query results to MenuItemPrice slice")
	}

	return o, nil
}

// Count returns the count of all MenuItemPrice records in the query.
func (q menuItemPriceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to count menu_item_prices rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q menuItemPriceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodel: failed to check if menu_item_prices exists")
	}

	return count > 0, nil
}

// MenuItem pointed to by the foreign key.
func (o *MenuItemPrice) MenuItem(mods ...qm.QueryMod) menuItemQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.MenuItemID),
	}

	queryMods = append(queryMods, mods...)

	return MenuItems(queryMods...)
}

// LoadMenuItem allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (menuItemPriceL) LoadMenuItem(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMenuItemPrice interface{}, mods queries.Applicator) error {
	var slice []*MenuItemPrice
	var object *MenuItemPrice

	if singular {
		var ok bool
		object, ok = maybeMenuItemPrice.(*MenuItemPrice)
		if !ok {
			object = new(MenuItemPrice)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMenuItemPrice)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMenuItemPrice))
			}
		}
	} else {
		s, ok := maybeMenuItemPrice.(*[]*MenuItemPrice)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMenuItemPrice)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMenuItemPrice))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &menuItemPriceR{}
		}
		args[object.MenuItemID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &menuItemPriceR{}
			}

			args[obj.MenuItemID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`menu_items`),
		qm.WhereIn(`menu_items.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load MenuItem")
	}

	var resultSlice []*MenuItem
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice MenuItem")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for menu_items")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for menu_items")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.MenuItem = foreign
		if foreign.R == nil {
			foreign.R = &menuItemR{}
		}
		foreign.R.MenuItemPrices = append(foreign.R.MenuItemPrices, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.MenuItemID == foreign.ID {
				local.R.MenuItem = foreign
				if foreign.R == nil {
					foreign.R = &menuItemR{}
				}
				foreign.R.MenuItemPrices = append(foreign.R.MenuItemPrices, local)
				break
			}
		}
	}

	return nil
}

// SetMenuItem of the menuItemPrice to the related item.
// Sets o.R.MenuItem to related.
// Adds o to related.R.MenuItemPrices.
func (o *MenuItemPrice) SetMenuItem(ctx context.Context, exec boil.ContextExecutor, insert bool, related *MenuItem) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"menu_item_prices\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"menu_item_id"}),
		strmangle.WhereClause("\"", "\"", 2, menuItemPricePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.MenuItemID = related.ID
	if o.R == nil {
		o.R = &menuItemPriceR{
			MenuItem: related,
		}
	} else {
		o.R.MenuItem = related
	}

	if related.R == nil {
		related.R = &menuItemR{
			MenuItemPrices: MenuItemPriceSlice{o},
		}
	} else {
		related.R.MenuItemPrices = append(related.R.MenuItemPrices, o)
	}

	return nil
}

// MenuItemPrices retrieves all the records using an executor.
func MenuItemPrices(mods ...qm.QueryMod) menuItemPriceQuery {
	mods = append(mods, qm.From("\"menu_item_prices\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"menu_item_prices\".*"})
	}

	return menuItemPriceQuery{q}
}

// FindMenuItemPrice retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMenuItemPrice(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*MenuItemPrice, error) {
	menuItemPriceObj := &MenuItemPrice{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"menu_item_prices\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, menuItemPriceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodel: unable to select from menu_item_prices")
	}

	return menuItemPriceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MenuItemPrice) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodel: no menu_item_prices provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(menuItemPriceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	menuItemPriceInsertCacheMut.RLock()
	cache, cached := menuItemPriceInsertCache[key]
	menuItemPriceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			menuItemPriceAllColumns,
			menuItemPriceColumnsWithDefault,
			menuItemPriceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(menuItemPriceType, menuItemPriceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(menuItemPriceType, menuItemPriceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"menu_item_prices\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"menu_item_prices\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodel: unable to insert into menu_item_prices")
	}

	if !cached {
		menuItemPriceInsertCacheMut.Lock()
		menuItemPriceInsertCache[key] = cache
		menuItemPriceInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the MenuItemPrice.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MenuItemPrice) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	menuItemPriceUpdateCacheMut.RLock()
	cache, cached := menuItemPriceUpdateCache[key]
	menuItemPriceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			menuItemPriceAllColumns,
			menuItemPricePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodel: unable to update menu_item_prices, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"menu_item_prices\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, menuItemPricePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(menuItemPriceType, menuItemPriceMapping, append(wl, menuItemPricePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to update menu_item_prices row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by update for menu_item_prices")
	}

	if !cached {
		menuItemPriceUpdateCacheMut.Lock()
		menuItemPriceUpdateCache[key] = cache
		menuItemPriceUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q menuItemPriceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to update all for menu_item_prices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to retrieve rows affected for menu_item_prices")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MenuItemPriceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), menuItemPricePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"menu_item_prices\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, menuItemPricePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to update all in menuItemPrice slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to retrieve rows affected all in update all menuItemPrice")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MenuItemPrice) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodel: no menu_item_prices provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(menuItemPriceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	menuItemPriceUpsertCacheMut.RLock()
	cache, cached := menuItemPriceUpsertCache[key]
	menuItemPriceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			menuItemPriceAllColumns,
			menuItemPriceColumnsWithDefault,
			menuItemPriceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			menuItemPriceAllColumns,
			menuItemPricePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodel: unable to upsert menu_item_prices, could not build update column list")
		}

		ret := strmangle.SetComplement(menuItemPriceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(menuItemPricePrimaryKeyColumns) == 0 {
				return errors.New("dbmodel: unable to upsert menu_item_prices, could not build conflict column list")
			}

			conflict = make([]string, len(menuItemPricePrimaryKeyColumns))
			copy(conflict, menuItemPricePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"menu_item_prices\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(menuItemPriceType, menuItemPriceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(menuItemPriceType, menuItemPriceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodel: unable to upsert menu_item_prices")
	}

	if !cached {
		menuItemPriceUpsertCacheMut.Lock()
		menuItemPriceUpsertCache[key] = cache
		menuItemPriceUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single MenuItemPrice record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MenuItemPrice) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodel: no MenuItemPrice provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), menuItemPricePrimaryKeyMapping)
	sql := "DELETE FROM \"menu_item_prices\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to delete from menu_item_prices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by delete for menu_item_prices")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q menuItemPriceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodel: no menuItemPriceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to delete all from menu_item_prices")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by deleteall for menu_item_prices")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MenuItemPriceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), menuItemPricePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"menu_item_prices\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, menuItemPricePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to delete all from menuItemPrice slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by deleteall for menu_item_prices")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MenuItemPrice) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMenuItemPrice(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MenuItemPriceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MenuItemPriceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), menuItemPricePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"menu_item_prices\".* FROM \"menu_item_prices\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, menuItemPricePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodel: unable to reload all in MenuItemPriceSlice")
	}

	*o = slice

	return nil
}

// MenuItemPriceExists checks if the MenuItemPrice row exists.
func MenuItemPriceExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"menu_item_prices\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodel: unable to check if menu_item_prices exists")
	}

	return exists, nil
}

// Exists checks if the MenuItemPrice row exists.
func (o *MenuItemPrice) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return MenuItemPriceExists(ctx, exec, o.ID)
}
